// Copyright 2026 dexploarer. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"prodigi-pp-cli/internal/client"
	"prodigi-pp-cli/internal/config"
)

// looksLikeAuthError checks if an error message body contains auth-related keywords.
func looksLikeAuthError(msg string) bool {
	lower := strings.ToLower(msg)
	patterns := []string{
		`\bkey\b`,
		`\btoken\b`,
		`\bunauthorized\b`,
		`\bapi_key\b`,
		`missing.{0,20}key`,
		`required.{0,20}key`,
		`\bforbidden\b`,
		`\bauthenticat`,
		`\bcredential`,
	}
	for _, p := range patterns {
		if matched, _ := regexp.MatchString(p, lower); matched {
			return true
		}
	}
	return false
}

// sanitizeErrorBody truncates and strips credential-shaped strings from error output.
func sanitizeErrorBody(msg string) string {
	if len(msg) > 200 {
		msg = msg[:200] + "..."
	}
	credPatterns := regexp.MustCompile(`(?i)(sk-[a-zA-Z0-9]{8,}|sk_live_[a-zA-Z0-9]+|Bearer\s+[a-zA-Z0-9._\-]+|key=[a-zA-Z0-9._\-]+)`)
	msg = credPatterns.ReplaceAllString(msg, "[REDACTED]")
	return msg
}

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("orders_cancel",
			mcplib.WithDescription("Cancel an order"),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The order identifier")),
		),
		makeAPIHandler("POST", "/Orders/{id}/actions/cancel", []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("orders_create",
			mcplib.WithDescription("Create a new order"),
			mcplib.WithString("body", mcplib.Description("JSON request body containing shippingMethod, recipient, items, metadata, branding, packingSlip, callbackUrl, merchantReference, and idempotencyKey")),
		),
		makeAPIHandler("POST", "/Orders", []string{}),
	)
	s.AddTool(
		mcplib.NewTool("orders_get",
			mcplib.WithDescription("Get an order by ID"),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The order identifier")),
		),
		makeAPIHandler("GET", "/Orders/{id}", []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("orders_get_actions",
			mcplib.WithDescription("Get the actions currently available for an order"),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The order identifier")),
		),
		makeAPIHandler("GET", "/Orders/{id}/actions", []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("orders_list",
			mcplib.WithDescription("Get orders Returns array."),
			mcplib.WithNumber("top", mcplib.Description("Maximum number of orders to return")),
			mcplib.WithNumber("skip", mcplib.Description("Number of orders to skip")),
			mcplib.WithString("createdFrom", mcplib.Description("Return orders created on or after this UTC DateTime")),
			mcplib.WithString("createdTo", mcplib.Description("Return orders created on or before this UTC DateTime")),
			mcplib.WithString("status", mcplib.Description("Filter orders by status stage")),
			mcplib.WithString("orderIds", mcplib.Description("Filter by one or more order IDs")),
			mcplib.WithString("merchantReferences", mcplib.Description("Filter by one or more merchant references")),
		),
		makeAPIHandler("GET", "/Orders", []string{}),
	)
	s.AddTool(
		mcplib.NewTool("orders_pause",
			mcplib.WithDescription("Pause an order"),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The order identifier")),
		),
		makeAPIHandler("POST", "/Orders/{id}/actions/pause", []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("orders_update_metadata",
			mcplib.WithDescription("Update the metadata of an order"),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The order identifier")),
			mcplib.WithString("body", mcplib.Description("JSON request body such as {\"metadata\":{\"key\":\"value\"}}")),
		),
		makeAPIHandler("POST", "/Orders/{id}/actions/updateMetadata", []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("orders_update_recipient",
			mcplib.WithDescription("Update the recipient of an order"),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The order identifier")),
			mcplib.WithString("body", mcplib.Description("JSON recipient body containing name, email, phoneNumber, and address")),
		),
		makeAPIHandler("POST", "/Orders/{id}/actions/updateRecipient", []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("orders_update_shipping_method",
			mcplib.WithDescription("Update the shipping method of an order"),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("The order identifier")),
			mcplib.WithString("shippingMethod", mcplib.Description("New shipping method: Budget, Standard, StandardPlus, Express, or Overnight")),
			mcplib.WithString("body", mcplib.Description("Optional JSON request body such as {\"shippingMethod\":\"Express\"}")),
		),
		makeAPIHandler("POST", "/Orders/{id}/actions/updateShippingMethod", []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("products_get",
			mcplib.WithDescription("Get product details by SKU"),
			mcplib.WithString("sku", mcplib.Required(), mcplib.Description("The product SKU")),
		),
		makeAPIHandler("GET", "/products/{sku}", []string{"sku"}),
	)
	s.AddTool(
		mcplib.NewTool("products_get_photobook_spine",
			mcplib.WithDescription("Get photobook spine details for a product"),
			mcplib.WithString("sku", mcplib.Required(), mcplib.Description("The photobook product SKU")),
			mcplib.WithString("destinationCountryCode", mcplib.Required(), mcplib.Description("Two-letter ISO destination country code")),
			mcplib.WithString("state", mcplib.Description("Destination state or county where required")),
			mcplib.WithNumber("numberOfPages", mcplib.Required(), mcplib.Description("Number of pages used to calculate spine dimensions")),
		),
		makeAPIHandler("POST", "/products/spine", []string{}),
	)
	s.AddTool(
		mcplib.NewTool("quotes_create",
			mcplib.WithDescription("Create a quote for one or more items"),
			mcplib.WithString("body", mcplib.Description("JSON request body containing destinationCountryCode, optional shippingMethod/currencyCode, and items")),
		),
		makeAPIHandler("POST", "/quotes", []string{}),
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
		),
		handleContext,
	)
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// Build path by substituting positional params
		path := pathTemplate
		for _, p := range positionalParams {
			if v, ok := req.Params.Arguments[p]; ok {
				path = strings.Replace(path, "{"+p+"}", fmt.Sprintf("%v", v), 1)
			}
		}

		// Collect non-positional params as query params or request body fields.
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for k, v := range req.Params.Arguments {
			isPositional := false
			for _, p := range positionalParams {
				if k == p {
					isPositional = true
					break
				}
			}
			if !isPositional {
				if method == "GET" {
					params[k] = fmt.Sprintf("%v", v)
				} else {
					bodyArgs[k] = v
				}
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, bodyErr := mcpRequestBody(bodyArgs)
			if bodyErr != nil {
				return mcplib.NewToolResultError(bodyErr.Error()), nil
			}
			data, _, err = c.Post(path, body)
		case "PUT":
			body, bodyErr := mcpRequestBody(bodyArgs)
			if bodyErr != nil {
				return mcplib.NewToolResultError(bodyErr.Error()), nil
			}
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, bodyErr := mcpRequestBody(bodyArgs)
			if bodyErr != nil {
				return mcplib.NewToolResultError(bodyErr.Error()), nil
			}
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && looksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + sanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export PRODIGI_API_KEY=<your-key>" +
					"\n      Run 'prodigi-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + sanitizeErrorBody(msg) +
					"\nhint: check your API key." +
					"\n      Set it with: export PRODIGI_API_KEY=<your-key>" +
					"\n      Run 'prodigi-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + sanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export PRODIGI_API_KEY=<your-key>" +
					"\n      Run 'prodigi-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func mcpRequestBody(args map[string]any) (any, error) {
	if raw, ok := args["body"]; ok {
		switch v := raw.(type) {
		case string:
			if strings.TrimSpace(v) == "" {
				return map[string]any{}, nil
			}
			var body any
			if err := json.Unmarshal([]byte(v), &body); err != nil {
				return nil, fmt.Errorf("parsing body JSON: %w", err)
			}
			return body, nil
		default:
			return v, nil
		}
	}
	if args == nil {
		return map[string]any{}, nil
	}
	return args, nil
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "prodigi-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	return client.New(cfg, 30*time.Second, 0), nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "prodigi-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "prodigi",
		"description": "CLI for prodigi",
		"archetype":   "generic",
		"tool_count":  12,
		"auth": map[string]any{
			"type":     "api_key",
			"env_vars": []string{"PRODIGI_API_KEY"},
		},
		"resources": []map[string]any{
			{
				"name":        "orders",
				"description": "Operations on orders",
				"endpoints":   []string{"cancel", "create", "get", "get_actions", "list", "pause", "update_metadata", "update_recipient", "update_shipping_method"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "products",
				"description": "Operations on products",
				"endpoints":   []string{"get", "get_photobook_spine"},
				"searchable":  true,
			},
			{
				"name":        "quotes",
				"description": "Operations on quotes",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}
