// Copyright 2026 dexploarer. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newOrdersCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyShippingMethod string
	var bodyRecipient string
	var bodyItems string
	var bodyMerchantReference string
	var bodyCallbackUrl string
	var bodyIdempotencyKey string
	var bodyBranding string
	var bodyPackingSlip string
	var bodyMetadata string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:     "create",
		Short:   "Create a new order",
		Example: "  prodigi-pp-cli orders create --shippingMethod example-value",
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("shipping-method") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "shipping-method")
				}
				if !cmd.Flags().Changed("recipient") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "recipient")
				}
				if !cmd.Flags().Changed("items") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "items")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/Orders"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyShippingMethod != "" {
					body["shippingMethod"] = bodyShippingMethod
				}
				if bodyRecipient != "" {
					value, err := parseJSONFlag("recipient", bodyRecipient)
					if err != nil {
						return err
					}
					body["recipient"] = value
				}
				if bodyItems != "" {
					value, err := parseJSONFlag("items", bodyItems)
					if err != nil {
						return err
					}
					body["items"] = value
				}
				if bodyMerchantReference != "" {
					body["merchantReference"] = bodyMerchantReference
				}
				if bodyCallbackUrl != "" {
					body["callbackUrl"] = bodyCallbackUrl
				}
				if bodyIdempotencyKey != "" {
					body["idempotencyKey"] = bodyIdempotencyKey
				}
				if bodyBranding != "" {
					value, err := parseJSONFlag("branding", bodyBranding)
					if err != nil {
						return err
					}
					body["branding"] = value
				}
				if bodyPackingSlip != "" {
					value, err := parseJSONFlag("packing-slip", bodyPackingSlip)
					if err != nil {
						return err
					}
					body["packingSlip"] = value
				}
				if bodyMetadata != "" {
					value, err := parseJSONFlag("metadata", bodyMetadata)
					if err != nil {
						return err
					}
					body["metadata"] = value
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping
				filtered := data
				if flags.compact {
					filtered = compactFields(filtered)
				}
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "orders",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyShippingMethod, "shipping-method", "", "Requested shipping method: Budget, Standard, StandardPlus, Express or Overnight")
	cmd.Flags().StringVar(&bodyRecipient, "recipient", "", "Shipping name and address")
	cmd.Flags().StringVar(&bodyItems, "items", "", "Items to be fulfilled (products + assets)")
	cmd.Flags().StringVar(&bodyMerchantReference, "merchant-reference", "", "Your own reference ID for this order")
	cmd.Flags().StringVar(&bodyCallbackUrl, "callback-url", "", "Your callback URL, where callback events are sent")
	cmd.Flags().StringVar(&bodyIdempotencyKey, "idempotency-key", "", "Your personal idempotency key")
	cmd.Flags().StringVar(&bodyBranding, "branding", "", "Per-order branding components")
	cmd.Flags().StringVar(&bodyPackingSlip, "packing-slip", "", "Packing slip")
	cmd.Flags().StringVar(&bodyMetadata, "metadata", "", "Custom JSON object of keys and values, up to 2000 characters")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
