// Copyright 2026 dexploarer. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strconv"

	"github.com/spf13/cobra"
)

func newProductsGetPhotobookSpineCmd(flags *rootFlags) *cobra.Command {
	var bodyDestinationCountryCode string
	var bodyState string
	var bodyNumberOfPages string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:     "get_photobook_spine <sku>",
		Short:   "Get photobook spine details for a product",
		Example: "  prodigi-pp-cli products get_photobook_spine BOOK-A4-L-HARD-M --destination-country-code US --state CA --number-of-pages 50",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("destination-country-code") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "destination-country-code")
				}
				if !cmd.Flags().Changed("number-of-pages") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "number-of-pages")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/products/spine"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{
					"sku": args[0],
				}
				if bodyDestinationCountryCode != "" {
					body["destinationCountryCode"] = bodyDestinationCountryCode
				}
				if bodyState != "" {
					body["state"] = bodyState
				}
				if bodyNumberOfPages != "" {
					numberOfPages, err := strconv.Atoi(bodyNumberOfPages)
					if err != nil {
						return fmt.Errorf("parsing --number-of-pages: %w", err)
					}
					body["numberOfPages"] = numberOfPages
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				filtered := data
				if flags.compact {
					filtered = compactFields(filtered)
				}
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "products",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyDestinationCountryCode, "destination-country-code", "", "Two-letter ISO destination country code")
	cmd.Flags().StringVar(&bodyState, "state", "", "Destination state or county where required")
	cmd.Flags().StringVar(&bodyNumberOfPages, "number-of-pages", "", "Number of pages used to calculate spine dimensions")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
