// Copyright 2026 dexploarer. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newOrdersPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagTop string
	var flagSkip string
	var flagCreatedFrom string
	var flagCreatedTo string
	var flagStatus string
	var flagOrderIds string
	var flagMerchantReferences string

	cmd := &cobra.Command{
		Use:     "orders",
		Short:   "Get orders",
		Long:    "Get orders with optional filters.",
		Example: "  prodigi-pp-cli orders",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/Orders"
			params := map[string]string{}
			if flagTop != "" {
				params["top"] = fmt.Sprintf("%v", flagTop)
			}
			if flagSkip != "" {
				params["skip"] = fmt.Sprintf("%v", flagSkip)
			}
			if flagCreatedFrom != "" {
				params["createdFrom"] = fmt.Sprintf("%v", flagCreatedFrom)
			}
			if flagCreatedTo != "" {
				params["createdTo"] = fmt.Sprintf("%v", flagCreatedTo)
			}
			if flagStatus != "" {
				params["status"] = fmt.Sprintf("%v", flagStatus)
			}
			if flagOrderIds != "" {
				params["orderIds"] = fmt.Sprintf("%v", flagOrderIds)
			}
			if flagMerchantReferences != "" {
				params["merchantReferences"] = fmt.Sprintf("%v", flagMerchantReferences)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagTop, "top", "", "Maximum number of orders to return")
	cmd.Flags().StringVar(&flagSkip, "skip", "", "Number of orders to skip")
	cmd.Flags().StringVar(&flagCreatedFrom, "created-from", "", "Return orders created on or after this UTC DateTime")
	cmd.Flags().StringVar(&flagCreatedTo, "created-to", "", "Return orders created on or before this UTC DateTime")
	cmd.Flags().StringVar(&flagStatus, "status", "", "Filter orders by status stage")
	cmd.Flags().StringVar(&flagOrderIds, "order-ids", "", "Filter by one or more order IDs")
	cmd.Flags().StringVar(&flagMerchantReferences, "merchant-references", "", "Filter by one or more merchant references")

	// Wire sibling endpoints and sub-resources as subcommands
	cmd.AddCommand(newOrdersCancelCmd(flags))
	cmd.AddCommand(newOrdersCreateCmd(flags))
	cmd.AddCommand(newOrdersGetCmd(flags))
	cmd.AddCommand(newOrdersGetActionsCmd(flags))
	cmd.AddCommand(newOrdersPauseCmd(flags))
	cmd.AddCommand(newOrdersUpdateMetadataCmd(flags))
	cmd.AddCommand(newOrdersUpdateRecipientCmd(flags))
	cmd.AddCommand(newOrdersUpdateShippingMethodCmd(flags))

	return cmd
}
