// Copyright 2026 dexploarer. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newProductsPromotedCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:     "products <sku>",
		Short:   "Get product details by SKU",
		Long:    "Get product details by SKU.",
		Example: "  prodigi-pp-cli products GLOBAL-CAN-10x10",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/products/{sku}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("sku is required\nUsage: %s %s <%s>", cmd.Root().Name(), cmd.CommandPath(), "sku"))
			}
			path = replacePathParam(path, "sku", args[0])
			params := map[string]string{}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}

	// Wire sibling endpoints and sub-resources as subcommands
	cmd.AddCommand(newProductsGetPhotobookSpineCmd(flags))

	return cmd
}
