// Copyright 2026 dexploarer. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

type toolOperation struct {
	Name        string   `json:"name"`
	Method      string   `json:"method"`
	Path        string   `json:"path"`
	Description string   `json:"description"`
	Required    []string `json:"required,omitempty"`
	ReadOnly    bool     `json:"read_only"`
}

func newToolCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tool",
		Short: "Machine-readable agent tool interface",
		Long:  "Machine-readable agent tool interface. All calls are non-interactive JSON in, JSON out.",
	}

	cmd.AddCommand(newToolSchemaCmd())
	cmd.AddCommand(newToolCallCmd(flags))
	return cmd
}

func newToolSchemaCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "schema",
		Short: "Print supported agent operations as JSON",
		RunE: func(cmd *cobra.Command, args []string) error {
			out, err := json.MarshalIndent(map[string]any{
				"tool":       "prodigi",
				"version":    version,
				"env":        []string{"PRODIGI_API_KEY", "PRODIGI_BASE_URL"},
				"operations": toolOperations(),
			}, "", "  ")
			if err != nil {
				return err
			}
			fmt.Fprintln(cmd.OutOrStdout(), string(out))
			return nil
		},
	}
}

func newToolCallCmd(flags *rootFlags) *cobra.Command {
	var inputJSON string
	var stdinInput bool

	cmd := &cobra.Command{
		Use:   "call <operation>",
		Short: "Call one Prodigi operation with JSON input",
		Example: `  prodigi-pp-cli tool call products.get --input '{"sku":"GLOBAL-CAN-10x10"}'
  prodigi-pp-cli tool call quotes.create --stdin < quote.json
  prodigi-pp-cli tool call orders.create --dry-run --stdin < order.json`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			input, err := parseToolInput(inputJSON, stdinInput)
			if err != nil {
				return err
			}
			op, ok := findToolOperation(args[0])
			if !ok {
				return usageErr(fmt.Errorf("unknown operation %q", args[0]))
			}
			if err := requireToolFields(op, input); err != nil {
				return usageErr(err)
			}

			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := op.Path
			for _, field := range op.Required {
				token := "{" + field + "}"
				if strings.Contains(path, token) {
					path = strings.ReplaceAll(path, token, fmt.Sprintf("%v", input[field]))
				}
			}

			var data json.RawMessage
			var statusCode int
			switch op.Method {
			case "GET":
				params := toolQueryParams(op, input)
				data, err = c.Get(path, params)
			case "POST":
				body, bodyErr := toolRequestBody(op.Name, input)
				if bodyErr != nil {
					return bodyErr
				}
				data, statusCode, err = c.Post(path, body)
			default:
				return fmt.Errorf("unsupported tool method %q", op.Method)
			}
			if err != nil {
				return classifyAPIError(err)
			}

			envelope := map[string]any{
				"operation": op.Name,
				"method":    op.Method,
				"path":      path,
				"success":   op.Method == "GET" || (statusCode >= 200 && statusCode < 300),
			}
			if op.Method != "GET" {
				envelope["status"] = statusCode
			}
			if flags.dryRun {
				envelope["dry_run"] = true
				envelope["success"] = false
			}
			if len(data) > 0 {
				var parsed any
				if err := json.Unmarshal(data, &parsed); err == nil {
					envelope["data"] = parsed
				}
			}
			out, err := json.MarshalIndent(envelope, "", "  ")
			if err != nil {
				return err
			}
			fmt.Fprintln(cmd.OutOrStdout(), string(out))
			return nil
		},
	}
	cmd.Flags().StringVar(&inputJSON, "input", "", "JSON input object for the operation")
	cmd.Flags().BoolVar(&stdinInput, "stdin", false, "Read JSON input object from stdin")
	return cmd
}

func toolOperations() []toolOperation {
	return []toolOperation{
		{Name: "products.get", Method: "GET", Path: "/products/{sku}", Description: "Get product details for a SKU, including attributes, print areas, variants, and print area sizes.", Required: []string{"sku"}, ReadOnly: true},
		{Name: "products.spine", Method: "POST", Path: "/products/spine", Description: "Calculate photobook spine width for a SKU, destination, and page count.", Required: []string{"sku", "destinationCountryCode", "numberOfPages"}, ReadOnly: true},
		{Name: "quotes.create", Method: "POST", Path: "/quotes", Description: "Create a quote for personalized items before order fulfillment.", Required: []string{"destinationCountryCode", "items"}, ReadOnly: true},
		{Name: "orders.list", Method: "GET", Path: "/Orders", Description: "List orders with optional filters.", ReadOnly: true},
		{Name: "orders.get", Method: "GET", Path: "/Orders/{id}", Description: "Get an order by Prodigi order ID.", Required: []string{"id"}, ReadOnly: true},
		{Name: "orders.actions", Method: "GET", Path: "/Orders/{id}/actions", Description: "Get currently available pre-fulfillment actions for an order.", Required: []string{"id"}, ReadOnly: true},
		{Name: "orders.create", Method: "POST", Path: "/Orders", Description: "Create a fulfillment order. Use sandbox and dry-run before live calls.", Required: []string{"shippingMethod", "recipient", "items"}, ReadOnly: false},
		{Name: "orders.cancel", Method: "POST", Path: "/Orders/{id}/actions/cancel", Description: "Cancel an order when cancellation is available.", Required: []string{"id"}, ReadOnly: false},
		{Name: "orders.pause", Method: "POST", Path: "/Orders/{id}/actions/pause", Description: "Pause an order when pause is available.", Required: []string{"id"}, ReadOnly: false},
		{Name: "orders.updateShippingMethod", Method: "POST", Path: "/Orders/{id}/actions/updateShippingMethod", Description: "Update an order shipping method before fulfillment locks it.", Required: []string{"id", "shippingMethod"}, ReadOnly: false},
		{Name: "orders.updateRecipient", Method: "POST", Path: "/Orders/{id}/actions/updateRecipient", Description: "Update recipient details before fulfillment locks them.", Required: []string{"id", "name", "address"}, ReadOnly: false},
		{Name: "orders.updateMetadata", Method: "POST", Path: "/Orders/{id}/actions/updateMetadata", Description: "Replace order metadata.", Required: []string{"id", "metadata"}, ReadOnly: false},
	}
}

func parseToolInput(inputJSON string, stdinInput bool) (map[string]any, error) {
	var raw []byte
	switch {
	case stdinInput:
		data, err := io.ReadAll(os.Stdin)
		if err != nil {
			return nil, fmt.Errorf("reading stdin: %w", err)
		}
		raw = data
	case inputJSON != "":
		raw = []byte(inputJSON)
	default:
		return map[string]any{}, nil
	}
	var input map[string]any
	if err := json.Unmarshal(raw, &input); err != nil {
		return nil, fmt.Errorf("parsing tool input JSON: %w", err)
	}
	return input, nil
}

func findToolOperation(name string) (toolOperation, bool) {
	for _, op := range toolOperations() {
		if op.Name == name {
			return op, true
		}
	}
	return toolOperation{}, false
}

func requireToolFields(op toolOperation, input map[string]any) error {
	for _, field := range op.Required {
		if _, ok := input[field]; !ok {
			return fmt.Errorf("operation %s requires input field %q", op.Name, field)
		}
	}
	return nil
}

func toolQueryParams(op toolOperation, input map[string]any) map[string]string {
	params := map[string]string{}
	for key, value := range input {
		if strings.Contains(op.Path, "{"+key+"}") {
			continue
		}
		params[key] = fmt.Sprintf("%v", value)
	}
	return params
}

func toolRequestBody(operation string, input map[string]any) (any, error) {
	body := copyToolInput(input)
	delete(body, "id")

	switch operation {
	case "orders.updateRecipient":
		return body, nil
	case "orders.updateMetadata":
		return map[string]any{"metadata": input["metadata"]}, nil
	case "orders.updateShippingMethod":
		return map[string]any{"shippingMethod": input["shippingMethod"]}, nil
	case "orders.cancel", "orders.pause":
		return map[string]any{}, nil
	default:
		return body, nil
	}
}

func copyToolInput(input map[string]any) map[string]any {
	out := make(map[string]any, len(input))
	for key, value := range input {
		out[key] = value
	}
	return out
}
